### ISSUE TITLE
mqtt: KeyError: 'pvenergytoday'

### ISSUE THREAD

**Issue by githubcdr** [johanmeijer/grott#204]
Hi,

After publishing a mqtt packet this error shos up;

```
         - Growatt packet received:
                  <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('10.4.0.96', 5279), raddr=('10.18.24.6', 1031)>

         - Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('10.4.0.96', 39164), raddr=('47.91.67.66', 5279)>
         - Growatt data decrypted V2
Traceback (most recent call last):
  File "grott.py", line 35, in <module>
    proxy.main(conf)
  File "/app/grottproxy.py", line 85, in main
    self.on_recv(conf)
  File "/app/grottproxy.py", line 165, in on_recv
    procdata(conf,data)
  File "/app/grottdata.py", line 420, in procdata
    "v1"    : definedkey["pvenergytoday"]*100,
KeyError: 'pvenergytoday'
```

Is this a bug?

**Comment by johanmeijer** [comment]
Hmm do you also have more information from the log. I need information on layout type being used and how the data record is processed to see what went wrong.

**Comment by githubcdr** [comment]
Hi,

I think this was related to a docker image I was using, after creating a new image it's working as expected!

Thanks for your help.
