### ISSUE TITLE
Grottserver crashes as soon as a new connection is made from a datalogger

### ISSUE THREAD

**Issue by Ihuarrax** [johanmeijer/grott#408]
Growattserver runs through a docker in Raspbian (buster).
The "server" service crashes with the following log (full log below) as soon a new/first connection is made:
"exception in server thread - close connection : [Errno 107] Socket not connected"
"Grottserver - exception in server thread - handle_writable_socket :  local variable 'client_address' referenced before assignment"

"client_address" variable is definitely set at one point because there is a log that says:
"Grottserver - Send queue created for : 127.0.0.1_59994"
The log seems to be create by the following code:
print(f"\t - Grottserver - Data received from : {client_address}:{client_port}")

I have two inverters that are the same model: MIN 10000TL-XH-US (ginvtype="min").
My Raspbian had to be configured with "47.251.35.20" (server-us.growatt.com) as a subinterface.
I have a static route on my router that makes my Raspbian the next hop for "47.251.35.20/32".
Raspbian sits on a different VLAN than the inverters to make sure the TCP traffic goes back through the same router.
I had to do it this way because I couldn't figure out how to make dataloggers (Inverter comes with a built-in wifi module ) go to a different FQDN/IP.
The inverters seem to use their own DNS servers instead of my local DNS server that resolves "server-us.growatt.com" to my Raspbian IP.
I share all this in case it has any impact on the server.

Having two inverters doesn't seem to be an issue because the server crashes before the second one attempts to send data.

TCP DUMP FROM THE ROUTER'S PERSPECTIVE:
====================================
13:46:10.156449 IP 10.0.100.102.50560 > 47.251.35.20.5279: Flags [.], ack 1, win 5840, length 0
13:46:10.165258 IP 10.0.100.102.50560 > 47.251.35.20.5279: Flags [P.], seq 1:41, ack 1, win 5840, length 40
13:46:10.166195 IP 47.251.35.20.5279 > 10.0.100.102.50560: Flags [.], ack 41, win 64200, length 0
13:46:10.223505 IP 47.251.35.20.5279 > 10.0.100.102.50560: Flags [F.], seq 1, ack 41, win 64200, length 0
13:46:10.223755 IP 10.0.100.102.50560 > 47.251.35.20.5279: Flags [.], ack 2, win 5839, length 0
13:46:12.922994 IP 10.0.100.102.50560 > 47.251.35.20.5279: Flags [P.], seq 41:626, ack 2, win 5839, length 585
13:46:12.923608 IP 47.251.35.20.5279 > 10.0.100.102.50560: Flags [R], seq 780695216, win 0, length 0
13:46:12.923663 IP 10.0.100.102.50560 > 47.251.35.20.5279: Flags [F.], seq 626, ack 2, win 5839, length 0
13:46:12.924095 IP 47.251.35.20.5279 > 10.0.100.102.50560: Flags [R], seq 780695216, win 0, length 0
13:47:12.974269 IP 10.0.100.102.50561 > 47.251.35.20.5279: Flags [S], seq 1301189139, win 5840, options [mss 1460], length 0
13:47:12.975336 IP 47.251.35.20.5279 > 10.0.100.102.50561: Flags [R.], seq 0, ack 1301189140, win 0, length 0
13:48:16.035580 IP 10.0.100.102.50562 > 47.251.35.20.5279: Flags [S], seq 1302114493, win 5840, options [mss 1460], length 0

DOCKER RUN COMMAND:
====================================
docker run --privileged -d -p 5279:5279 -p 5782:5782 --name grottserver --restart on-failure -e ginvtype="min" -e gblockcmd="True" -e gminrecl="1" -e ginflux="True" -e gifip="10.0.0.230" -e gnomqtt="True" -e gpvoutput="True" -e gpvapikey="***********************" -e gpvsystemid="******"  ledidobe/grottserverrpi

LOG:
====================================
Grott proxy mode started
Hostname : ba3fbc5ba4bc
IP :  172.17.0.2 , port :  5279

         - ('10.0.100.102', 50560) has connected
         - Grottserver - Socket connection received from ('127.0.0.1', 59994)
         - Grottserver - Send queue created for : 127.0.0.1_59994
         - Grottserver - input received:  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 5781)>

         - Growatt packet received:
                  <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 59994), raddr=('127.0.0.1', 5781)>
         - Growatt command block checking started
Traceback (most recent call last):
  File "/app/grott.py", line 35, in <module>
    proxy.main(conf)
  File "/app/grottproxy.py", line 87, in main
    self.on_recv(conf)
  File "/app/grottproxy.py", line 169, in on_recv
    if len(data) > conf.minrecl :
TypeError: '>' not supported between instances of 'int' and 'str'
         - Grottserver - Data received from : 127.0.0.1:59994
         - Grottserver - Original Data:
                 \x68\xd2\x00\x06\x00\x20\x01\x16\x11\x31\x5a\x47\x51\x45\x44\x72\x43\x57\x44
                 \x55\x44\x44\x7f\x4b\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72
                 \xca\xff
         - Grott - data decrypted V2
         - Grottserver - Plain record:
                 68d2000600200116564335303031303531383334303038390000000000000000000000000000a
                 588
         - Grottserver - 16 - Ping response:
                 \x68\xd2\x00\x06\x00\x20\x01\x16\x11\x31\x5a\x47\x51\x45\x44\x72\x43\x57\x44
                 \x55\x44\x44\x7f\x4b\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72
                 \xca\xff
         - Grottserver - Put response on queue:  127.0.0.1_59994  msg:
                 \x68\xd2\x00\x06\x00\x20\x01\x16\x11\x31\x5a\x47\x51\x45\x44\x72\x43\x57\x44
                 \x55\x44\x44\x7f\x4b\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72
                 \xca\xff
         - Grottserver - get response from queue:  127.0.0.1_59994 msg:
                 \x68\xd2\x00\x06\x00\x20\x01\x16\x11\x31\x5a\x47\x51\x45\x44\x72\x43\x57\x44
                 \x55\x44\x44\x7f\x4b\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72
                 \xca\xff
         - Grottserver - Close connection :  <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5781)>
         - Grottserver - exception in server thread - close connection : [Errno 107] Socket not connected
         - Grottserver - socket closed :
         - Grottserver - exception in server thread - handle_writable_socket :  local variable 'client_address' referenced before assignment

**Comment by Ihuarrax** [comment]
I think I have focused too much on the last few logs and missed the fact that "server" is still listening.
This issue seems to be related to "grott" as opposed to "grottserver".
The "grott" error happens much sooner and says:

 File "/app/grottproxy.py", line 169, in on_recv
    if len(data) > conf.minrecl :
TypeError: '>' not supported between instances of 'int' and 'str'

**Comment by Ihuarrax** [comment]
The issue was resolved by removing "gminrecl="1"" from the docker run command

**Comment by Ihuarrax** [comment]
The issue was resolved by removing "gminrecl="1"" from the docker run command
