### ISSUE TITLE
Time error in timestamp - grott stops

### ISSUE THREAD

**Issue by raadjek** [johanmeijer/grott#606]
I'm running Grott for quite some time without issues. This issue happened first last weekend when the summer time ended (was away and got to investigation only now). I saw no records in HA neither in ShinePhone app (or server.growatt.com).

I found that the Grott integration stops when it receives record with timestamp off by 3 days. The config says "gtime = server", so it should be ignored, but obviously it throws it off.

```
 Add-on: Grott Beta branch (2.8)
 The Growatt inverter monitor with current HA plugin integrated
-----------------------------------------------------------
 Add-on version: 0.1.5
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.2  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2024.10.4
 Home Assistant Supervisor: 2024.10.3
```

 The log says (the OK part - with correct-ish time):
```
	 - MQTT jsonmsg: 
			 {"device": "TNJ2BLH00U", "time": "2024-10-30T16:36:13", "buffered": "no",
			 "values": {"datalogserial": "XGD5BH34AJ", "pvserial": "TNJ2BLH00U",
			 "pvstatus": 6, "pvpowerin": 0, "pv1voltage": 0, "pv1current": 0, "pv1watt":
			 0, "pv2voltage": 0, "pv2current": 0, "pv2watt": 0, "pvpowerout": 6851,
			 "pvfrequentie": 4999, "pvgridvoltage": 4139, "pvgridcurrent": 19,
			 "pvgridpower": 8029, "pvgridvoltage2": 4177, "pvgridcurrent2": 11,
			 "pvgridpower2": 0, "pvgridvoltage3": 4161, "pvgridcurrent3": 12,
			 "pvgridpower3": 0, "totworktime": 146174103, "eactoday": 52,
			 "pvenergytoday": 52, "eactotal": 139950, "epvtotal": 147392, "epv1today":
			 66, "epv1total": 147392, "epv2today": 0, "epv2total": 0, "pvtemperature":
			 410, "pvipmtemperature": 383, "pvboosttemp": 384, "bat_dsp": 2627,
			 "eacharge_today": 10, "eacharge_total": 19310, "batterytype": 1,
			 "uwsysworkmode": 6, "systemfaultword0": 0, "systemfaultword1": 0,
			 "systemfaultword2": 0, "systemfaultword3": 0, "systemfaultword4": 32,
			 "systemfaultword5": 0, "systemfaultword6": 0, "systemfaultword7": 0,
			 "pdischarge1": 8800, "p1charge1": 0, "vbat": 2629, "SOC": 61, "pactouserr":
			 0, "pactousertot": 0, "pactogridr": 600, "pactogridtot": 600, "plocaloadr":
			 8200, "plocaloadtot": 8200, "spdspstatus": 6, "spbusvolt": 7347,
			 "etouser_tod": 7, "etouser_tot": 55570, "etogrid_tod": 10, "etogrid_tot":
			 46054, "edischarge1_tod": 50, "edischarge1_tot": 58574, "eharge1_tod": 46,
			 "eharge1_tot": 62872, "elocalload_tod": 67, "elocalload_tot": 151085}}
	 - Grott MQTT topic used : energy/growatt
	 - MQTT message message sent
	 - Grott Send data to PVOutput disabled 
	 - Grott InfluxDB publihing started
	 - Grott original time :  2024-10-30T16:36:13 adjusted UTC time for influx :  2024-10-30T15:36:13
	 - Grott influxdb jsonmsg: 
			 [{'measurement': 'TNJ2BLH00U', 'time': '2024-10-30T15:36:13', 'fields':
			 {'datalogserial': 'XGD5BH34AJ', 'pvserial': 'TNJ2BLH00U', 'pvstatus': 6,
			 'pvpowerin': 0, 'pv1voltage': 0, 'pv1current': 0, 'pv1watt': 0,
			 'pv2voltage': 0, 'pv2current': 0, 'pv2watt': 0, 'pvpowerout': 6851,
			 'pvfrequentie': 4999, 'pvgridvoltage': 4139, 'pvgridcurrent': 19,
			 'pvgridpower': 8029, 'pvgridvoltage2': 4177, 'pvgridcurrent2': 11,
			 'pvgridpower2': 0, 'pvgridvoltage3': 4161, 'pvgridcurrent3': 12,
			 'pvgridpower3': 0, 'totworktime': 146174103, 'eactoday': 52,
			 'pvenergytoday': 52, 'eactotal': 139950, 'epvtotal': 147392, 'epv1today':
			 66, 'epv1total': 147392, 'epv2today': 0, 'epv2total': 0, 'pvtemperature':
			 410, 'pvipmtemperature': 383, 'pvboosttemp': 384, 'bat_dsp': 2627,
			 'eacharge_today': 10, 'eacharge_total': 19310, 'batterytype': 1,
			 'uwsysworkmode': 6, 'systemfaultword0': 0, 'systemfaultword1': 0,
			 'systemfaultword2': 0, 'systemfaultword3': 0, 'systemfaultword4': 32,
			 'systemfaultword5': 0, 'systemfaultword6': 0, 'systemfaultword7': 0,
			 'pdischarge1': 8800, 'p1charge1': 0, 'vbat': 2629, 'SOC': 61, 'pactouserr':
			 0, 'pactousertot': 0, 'pactogridr': 600, 'pactogridtot': 600, 'plocaloadr':
			 8200, 'plocaloadtot': 8200, 'spdspstatus': 6, 'spbusvolt': 7347,
			 'etouser_tod': 7, 'etouser_tot': 55570, 'etogrid_tod': 10, 'etogrid_tot':
			 46054, 'edischarge1_tod': 50, 'edischarge1_tot': 58574, 'eharge1_tod': 46,
			 'eharge1_tot': 62872, 'elocalload_tod': 67, 'elocalload_tot': 151085}}]
	 - Grott write to influxdb v1
	 - Grott extension processing disabled 

	 - Growatt packet received:
		  <socket.socket fd=6, family=2, type=1, proto=0, laddr=('172.30.33.8', 5279), raddr=('192.168.1.142', 27903)>
	 - Data less then minimum record length, data not processed

	 - Growatt packet received:
		  <socket.socket fd=5, family=2, type=1, proto=0, laddr=('172.30.33.8', 58870), raddr=('8.209.71.240', 5279)>
	 - Data less then minimum record length, data not processed

	 - Growatt packet received:
		  <socket.socket fd=6, family=2, type=1, proto=0, laddr=('172.30.33.8', 5279), raddr=('192.168.1.142', 27903)>
	 - Data less then minimum record length, data not processed

	 - Growatt packet received:
		  <socket.socket fd=5, family=2, type=1, proto=0, laddr=('172.30.33.8', 58870), raddr=('8.209.71.240', 5279)>
	 - Data less then minimum record length, data not processed

	 - Growatt packet received:
		  <socket.socket fd=5, family=2, type=1, proto=0, laddr=('172.30.33.8', 58870), raddr=('8.209.71.240', 5279)>
- Data less then minimum record length, data not processed
```
Those are records with correct (mostly) timestamps. But then I see also this:
```
	 - MQTT jsonmsg: 
			 {"device": "TNJ2BLH00U", "time": "2024-10-27T02:10:13", "buffered": "yes",
			 "values": {"datalogserial": "XGD5BH34AJ", "pvserial": "TNJ2BLH00U",
			 "pvstatus": 6, "pvpowerin": 0, "pv1voltage": 0, "pv1current": 0, "pv1watt":
			 0, "pv2voltage": 0, "pv2current": 0, "pv2watt": 0, "pvpowerout": 2693,
			 "pvfrequentie": 5001, "pvgridvoltage": 4200, "pvgridcurrent": 9,
			 "pvgridpower": 5645, "pvgridvoltage2": 4243, "pvgridcurrent2": 6,
			 "pvgridpower2": 0, "pvgridvoltage3": 4218, "pvgridcurrent3": 7,
			 "pvgridpower3": 0, "totworktime": 145544799, "eactoday": 5, "pvenergytoday":
			 5, "eactotal": 139586, "epvtotal": 146976, "epv1today": 0, "epv1total":
			 146976, "epv2today": 0, "epv2total": 0, "pvtemperature": 382,
			 "pvipmtemperature": 354, "pvboosttemp": 351, "bat_dsp": 2612,
			 "eacharge_today": 4, "eacharge_total": 19181, "batterytype": 1,
			 "uwsysworkmode": 6, "systemfaultword0": 0, "systemfaultword1": 0,
			 "systemfaultword2": 0, "systemfaultword3": 0, "systemfaultword4": 32,
			 "systemfaultword5": 0, "systemfaultword6": 0, "systemfaultword7": 0,
			 "pdischarge1": 4400, "p1charge1": 0, "vbat": 2614, "SOC": 28, "pactouserr":
			 0, "pactousertot": 0, "pactogridr": 600, "pactogridtot": 600, "plocaloadr":
			 3800, "plocaloadtot": 3800, "spdspstatus": 6, "spbusvolt": 7452,
			 "etouser_tod": 0, "etouser_tot": 55441, "etogrid_tod": 1, "etogrid_tot":
			 45872, "edischarge1_tod": 9, "edischarge1_tot": 58366, "eharge1_tod": 0,
			 "eharge1_tot": 62608, "elocalload_tod": 9, "elocalload_tot": 150777}}
	 - Grott MQTT topic used : energy/growatt
	 - MQTT message message sent
	 - Grott Send data to PVOutput disabled 
	 - Grott InfluxDB publihing started
Traceback (most recent call last):
  File "/app/grott.py", line 35, in <module>
    proxy.main(conf)
  File "/app/grottproxy.py", line 144, in main
    self.on_recv(conf)
  File "/app/grottproxy.py", line 238, in on_recv
    procdata(conf,data)    
    ^^^^^^^^^^^^^^^^^^^
  File "/app/grottdata.py", line 615, in procdata
    local_dt = local.localize(naive, is_dst=None)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pytz/tzinfo.py", line 366, in localize
    raise AmbiguousTimeError(dt)
pytz.exceptions.AmbiguousTimeError: 2024-10-27 02:10:13
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```
And the Grott stops. Sometimes it starts again (watchdog?), sometimes not.
The date reported is 2024-10-27, while today it 2024-10-30. 
I tried to set the inverter time using ShinePhone app, which seems to be OK (the command is performed), but have no idea where _some_ records take the wrong date from.

Grott config (I'm using GUI) is:
```
data_path: /config/grott
gmode: proxy
grott_mqtt: true
ginvtype: sph
ginvtypemap: ""
retain: true
verbose: true
ha_plugin: false
mqtt: {}
gifdbname: grottdb
gifip: 192.168.1.24
gifpassword: ****
gifport: 8086
gifuser: grottdbuser
ginflux: true
ginverterid: TNJ2BLH00U
gmqttauth: false
gextension: false
gtime: server
gtimezone: Europe/Prague
ggrowattip: 8.209.71.240
ggrowattport: 5279
gnoipf: true
gmqttuser: mqttuser
```

I tried stable branch of Grott (0.1.12) as well (normally I use Beta, but I have a feeling this is not related to Grott as such (except that Grott could ignore the wrong time).

Any pointers?

**Comment by raadjek** [comment]
So, according to latest log it seems the datetime stamp is not the reason. Grott stops even with correct date time or without json message.
`	 - Growatt packet received:
		  <socket.socket fd=5, family=2, type=1, proto=0, laddr=('172.30.33.8', 42274), raddr=('8.209.71.240', 5279)>

	 - Growatt packet received:
		  <socket.socket fd=5, family=2, type=1, proto=0, laddr=('172.30.33.8', 42274), raddr=('8.209.71.240', 5279)>

	 - Growatt packet received:
		  <socket.socket fd=5, family=2, type=1, proto=0, laddr=('172.30.33.8', 42274), raddr=('8.209.71.240', 5279)>
	 - Growatt data decrypted V2
	 - Grott MQTT topic used : energy/growatt
Traceback (most recent call last):
  File "/app/grott.py", line 35, in <module>
    proxy.main(conf)
  File "/app/grottproxy.py", line 144, in main
    self.on_recv(conf)
  File "/app/grottproxy.py", line 238, in on_recv
    procdata(conf,data)    
    ^^^^^^^^^^^^^^^^^^^
  File "/app/grottdata.py", line 615, in procdata
    local_dt = local.localize(naive, is_dst=None)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pytz/tzinfo.py", line 366, in localize
    raise AmbiguousTimeError(dt)
pytz.exceptions.AmbiguousTimeError: 2024-10-27 02:10:13
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped`

**Comment by johanmeijer** [comment]
This is strange. Do you want to keep the buffered records? If not can you try it with 

    sendbuf = False 

in the grott.ini [Generic] section? 

Seeing the fact dat you use the HA addon it is not possible for me to debug. It can be some time settings in the HA environment.

**Comment by raadjek** [comment]
I have set 
`sendbuf = False`
and also set in GUI value 
`retain=false`   (Activate MQTT Retain)
and removed `mqttuser` from gui.

Looks like it works now - at least for last 24+ hours.

**Comment by raadjek** [comment]
No issues  since then. Closing this topic. Thanks for your help.
